### PR TITLE
- Fixed sampleide completion to bring up popup after . instead

### PR DESCRIPTION
**Pull request by zjnue**

### CODE REVIEW

**Comment by soywiz** [comment]
Uhm. I think I did that change to avoid getting the default autocompletors that added "local", and "keyword" stuff, being local repeated (without type information) or event from non-accessible scopes. So that's why I overrided all the completers to just use mine. I could add keyword information related to the current scope, so you can't use por example "class" or "import" inside a method. What do you think about that? Should I revert this or there is a reason for that?

The "." should work sometimes at this point, since in some cases the parser can't recover and doesn't provide good information. But for example if you put class A { function test() { this.###; } } this should work. I'm working on improving error recovery so it works in more cases, also at this point is very hacky since it just provide completion after the dot and probably should extend that to word boundaries to get completion after a whole identifier.

**Comment by zjnue** [comment]
Aha, very interesting - thank you for the explanation. My change didn't consider anything as advanced. I simply tried the sample code in your Haxe ML announcement and added `this.` as the last statement inside the demo method. Before the change, completion immediately added the demo field (creating `this.demo`) without bringing up a popup. My change caused the popup to appear instead. I understand now why you overwrote the default completers and compiling your latest fix to this adds only the two sensible fields to the popup for this example, namely `demo` and `test2`, so please do continue with that. Happy coding!

**Comment by soywiz** [comment]
@zjnue I have implemented a function call assistant http://soywiz.github.io/hxlanguageservices/
Do you know if ACE has apis (or there is any extension) to show function calling information? Atm I'm just displaying it in the sidebar, but it would be great to display it below the cursor just like other IDEs do.

**Comment by zjnue** [comment]
Sounds like a great addition! I don't know ACE and from a quick look I cannot see direct support, but perhaps something along the [lines of TokenTooltip](https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/demo.js#L519-L527) for the [Kitchen Sink Demo](http://ace.c9.io/build/kitchen-sink.html) (select "Show token info") could be re-used or simulated for function call info? Will look into it more a bit later.

**Pull request merged**
