### PR TITLE
quick attempt at slightly better enum parsing

### PR DESCRIPTION
**Pull request by zjnue**
Hi, great to see you got the function call stuff working. Not heaps of available time here sadly, but here's a small token gesture at least. Could be far off though - I'm assuming the name:ZNode in NEnum consumes the enum identifier only and we need another expr in there for the block (assumptions based on hscript designs..). Anyway, please feel free to ignore.

### CODE REVIEW

**Comment by zjnue** [comment]
Ok, this is turning into a mess but the parsing seems closer to acceptable enum syntax as I understand. Will wait with further help when there is time. Potentially much later ;) Happy coding.

**Comment by soywiz** [comment]
Thanks. It seems fine to me. Merging.

I know my code is bit mess at this point.
The idea is iterating and refactoring having tests validating behaviour. So I will be able to do a couple of huge refactoring s and cleanups before an acceptable version comes up.

**Comment by zjnue** [comment]
Thanks, but please - you misunderstood. It is My code that is the mess - using 5 commits for a trivial change -just because I don't take a little more time to gain a better understanding of the internal workings first. That said, I know it is nice to move past the parsing stage, so I might try to add another small sprinkle here and there in this style, if it helps. My hope is that these messy commits will disappear from collective memory soon, so not too precious about them, as should be clear already :)

**Comment by soywiz** [comment]
Oh, I see. Don't worry. Every contribution is highly appreciated! And the value of something, even small is not measured for its quality or if it is more elegant than other stuff, but as a step forward towards one goal; and your commits are moving forward to the goal of improving the syntax parsing. So thank you.

**Comment by zjnue** [comment]
Sounds great - it's a pleasure.

**Pull request merged**
